# Generated by Django 4.0.3 on 2022-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_movie_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='currency',
        ),
        migrations.AddField(
            model_name='movie',
            name='choices',
            field=models.CharField(choices=[('E', 'Euro'), ('D', 'Dollars'), ('R', 'Rubles')], default='R', max_length=2),
        ),
    ]
