# Generated by Django 4.0.3 on 2022-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_remove_movie_currency_movie_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='choices',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollars'), ('RUB', 'Rubles')], default='RUB', max_length=3),
        ),
    ]
